language: objective-c
before_install: 
  - sudo easy_install pip
  - brew install libyaml
  - sudo pip install -r ./requirements.txt
  - sudo pip install nose
  - sudo gem install cocoapods
  - "cd FrodoTest && pod install && cd -"
before_script:
  - export LANG=en_US.UTF-8
script: ./test.sh
